# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ParseSetup' do

pod 'Parse'

pod 'Onboard'

pod 'RESideMenu', '~> 4.0.7'

pod 'UIColor_Hex_Swift', '~> 2.1'

end

